FROM python:3

WORKDIR /usr/src/app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y

WORKDIR /root

#
# Need this to convert audio files to an acceptable format
#
RUN apt-get install -y ffmpeg

#
# Allosaurus
#
RUN pip install allosaurus

#
# Script
#
COPY lib/allosaurus-infer.sh /root

#
# BATS: Bash Automated Testing System
#
WORKDIR /root
RUN git clone https://github.com/sstephenson/bats.git
RUN cd bats && ./install.sh /usr/local

COPY spec/allosaurus/ /root/tests

#
# This just downloads the pretrained model so that it doesn't need to happen on
# first execution.
#
RUN ./allosaurus-infer.sh /root/tests/audio/hello-world.wav

#
# SSH
#
EXPOSE 22
RUN apt-get install -y openssh-server
# This allows ssh with root
RUN sed -i 's/#StrictModes yes/StrictModes no/g' /etc/ssh/sshd_config
ENTRYPOINT service ssh restart && bash


